development:
  adapter: postgresql
  database: sampleTicketDevNew
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost
  
test: &TEST
  adapter: postgresql
  database: sampleTicketTest
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost

production:
  adapter: postgresql
  database: sampleTicketNew
  pool: 16
  encoding: su
  username: su
  password: AquSoftBistro
  host: localhost
  
cucumber:
  <<: *TEST
