development:
  adapter: postgresql
  database: postgres
  username: su
  password: su
  host: localhost
  
test: &TEST
  adapter: postgresql
  database: postgres
  username: su
  password: su
  host: localhost

production:
  adapter: postgresql
  database: postgres
  username: su
  password: su
  host: localhost
  
cucumber:
  <<: *TEST
