development:
  adapter: postgresql
  database: aqupostgres
  encoding: unicode
  pool: 16
  username: aqusu
  password: AquSoftBistro
  host: aqu-postgre.cchjybjthc9l.us-west-2.rds.amazonaws.com
  
test: &TEST
  adapter: postgresql
  database: aqutestpg
  encoding: unicode
  pool: 16
  username: aqusu
  password: AquSoftBistro
  host: aqupostgres-test.cchjybjthc9l.us-west-2.rds.amazonaws.com

production:
  adapter: postgresql
  database: aqupostgres
  pool: 16
  encoding: unicode
  username: aqusu
  password: AquSoftBistro
  host: aqu-postgre.cchjybjthc9l.us-west-2.rds.amazonaws.com
  
cucumber:
  <<: *TEST
