development:
  adapter: postgresql
  database: sampleTicketDev
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost
  
test: &TEST
  adapter: postgresql
  database: sampleTicketTest
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost

production:
  adapter: sampleTicket
  database: postgres
  pool: 16
  encoding: unicode
  username: su
  password: su
  host: localhost
  
cucumber:
  <<: *TEST
